### PR TITLE
moo-job-k5l0jq AI CI Job

### PR DESCRIPTION
**Pull request by moo-ai**
Reproduce ML environment via OpenLab

### CODE REVIEW

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Comment by moo-ai** [comment]
recheck

**Pull request closed without merging**
